# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0002_branch_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='code',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='ifsc',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
